---
title: "Abstracts"
---

<div style="padding:10px;font-size:2em;background:#fdddff;color:#001e05">
[参加申し込み](https://gkb.jp/visitor/seminar/318)した方にのみ、ZOOM ID をメールでお知らせいたします。
</div>

## 発表者 1

井出育子

### Title

線維筋痛症患者における季節性疼痛に関する当事者研究 ――春期と梅雨期の比較――

### Abstract

本研究は、線維筋痛症を患う研究者本人の疼痛記録を、天候状況と共に記録、比較分析し、関連性について調べた。同時に自らの病状を主体的に捉えるアプローチとしての当事者研究の有用性について検討した。

研究期間中の疼痛の程度をVASを用いて記録し、体温・SpO2、痛みや症状については記述式で記録した。気温・湿度・気圧を計測し、気候変化と症状の関連を調査するため、春季と梅雨期で実施した。

その結果、気圧と痛みに関連性が観察され、その相関係数 R２は 0.036 であった。気圧の変動が大きいときに不調が多いことが観察された。春季と梅雨期の気象条件に有意差は認められなかった。

自らの病状を主体的にコントロールすることは、患者本人のQOLの向上や症状の緩和法に有用である。今後方法論の改善等により、本研究が患者の疼痛管理の助けとなり、当事者研究の普及に寄与することを期待する。

## 発表者 2

峰村直樹 (デイサービスセンター　長寿村)

### Title

もの忘れ相談プログラム実施に対する課題と提言 合理的配慮の提供義務化から

### Abstract

【目的】「もの忘れ相談プログラム」（以下、MSP）実施上の合理的配慮が必要な課題箇所と提言を行う。

【方法】R５年度一般介護予防事業参加者 103 名と事業担当者にアンケート調査と「みんなの聴脳力®チェック」（以下、アプリ）を実施した。

【結果】アンケート結果では、「小声で話しかけられたとき（55％）」、「人混みの中での会話（54％）」が聞き取りにくいと回答し、アプリは平均 58.6±25 点であった。

【考察】MSP はヘッドホンを装着し実施するが、「短期記憶」テストのみ文字の表示がなく聴覚情報だけを頼りに記憶し解答する。視覚情報がなければ、難聴や暗騒音による「聞き取り間違い」があることは否定できない。合理的配慮から文字を表示する必要性を提言する。

【倫理的配慮】学会発表にあたり、ご本人に趣旨を説明し承諾を得た。


## 発表者 3

青木和人

### Title

メタ分析を用いた要介護度の地域間差異に関する研究

### Abstract

日本における高齢化の進展に伴い、要介護認定を受ける高齢者の数が増加している。その要因として、介護従事者の都市部と郊外部への交通アクセスの違いや、地域特有の介護政策の影響が考えられる。しかし、要介護度の地域間差異に関する研究は個別のケーススタディが多く、統合的な分析が不足している。そこで本研究では、要介護度の変遷に関する過去の研究や行政データを統合し、メタ分析を用いて日本における要介護度の地域間差異を明らかにすることを目的とする。

As the aging of the population progresses in Japan, the number of elderly people certified as requiring nursing care is increasing. Possible reasons for this include differences in transportation access for care workers between urban and suburban areas, and the influence of regional nursing care policies. However, most research on regional differences in the level of care required has been individual case studies, and comprehensive analysis is lacking. Therefore, this study aims to integrate past research and administrative data on the transition of levels of care required, and to use meta-analysis to clarify regional differences in levels of care required in Japan.

## 発表者 4

前野優太 (株式会社 七夢)、板垣篤典

### Title

寝たきり高齢者に対する介護士による臥位ポジショニングが体圧分布に及ぼす影響

### Abstract

【背景】
ポジショニング前後の体圧測定を用いた定量評価は理学・作業療法士を中心に行われている。一方、生活の場で提供される介護士によるポジショニングについてはその定量的評価に基づく効果の議論は十分になされていない。

【目的】
介護士がベッド上のポジショニングで介入した前後の体圧変化をモニタリングし、その効果を検証する。

【方法】
80歳代後半男性、重度アルツハイマー型認知症、要介護5、寝たきり度C2の対象者に、介護士(職歴６年)がポジショニング前後の圧データの変化を全身体圧計のSRソフトビジョン(住友理工)を用いて記録した。

【結果】
介入前後の変化について。最大体圧が58から47mmHgへ減少、平均体圧が26.6±12.0から23.8±9.6mmHgへ減少、検知面積が329から417セルへ増加、臥位での褥瘡リスクとされる32mmHgを超える圧を検知したセルの割合が40.1から24.0％へ減少した。

## 発表者 5

大庭 康二 (グループホーム第二光喜園)

### Title

認知症高齢者に対する介護の関わり合い

### Abstract

攻撃性などのBPSDの対応について、向精神薬が処方されるケースが多くみられることから、薬剤に頼ることなくBPSDの改善を図ることで、当事業所の目標である「向精神薬の減薬」することを目的とした。

対象者は、妄想や攻撃性などのBPSD利用者１名対象期間はR6 １1月～R7 3月の4ヵ月とする。

研究方法として、不穏になった際の対応を5つの方法を用いて行う。

① おとなしくなるまで見守る

② 目先を変える

③ 一緒になって対象物に怒る

④ ひたすら付き沿う

⑤ 利用者の話を反復する

結果

➀②に関しては、落ち着いたとしても不穏が再現するケースが多い

③④⑤に関しては、不穏が再現するケースは➀②に比べ少ない

上記の事から考察すると暴力などは目先の対応でなく気持ち的なものが大きくかかわることがわかる。

認知症になると言語的な意思の疎通が苦手になる反面、対応する職員の内面的な感情が認知症を有する方には伝わりやすくなっているのだと推測される。

## 発表者 6

住永みどり (南阿蘇居宅支援事業所)

### Title

訪問介護サービスにおける生産性向上を考える ――訪問介護の経営に関する文献検討から――

### Abstract

本研究は，訪問介護の経営に関する過去の論文を概観し，研究の動向を明らかにするとともに，生産性向上との関係性を考察することを目的とする。
使用するデータベースは，医学中央雑誌Web，CiNii Research，検索ワードは「訪問介護」「経営」とした。調査実施期間は2024年 4月1日～ 2024年6月30日。調査に際しての倫理的留意としてPRISMA2020声明に則った。

結果として，【利益の確保】【経営主体：非営利事業者・営利事業者の比較】【質の確保】【移動の問題】が訪問介護事業所の経営に必要とされる要因として関連があり，これらのカテゴリーは、厚生労働省が示す介護サービスにおける生産性向上ガイドラインの3つの観点に関連していることが示唆された。

## リザーブ 1

佐々木毅然

### Title

**中高齢者の生涯にわたる健康生活のための自転車活用に関する検討**<br>
 - 主観的運動強度を用いた介入について -

### Abstract

**背景:** 日本人の平均寿命と健康寿命の差は大きく、介助や介護が必要となる期間が長い。生活習慣病の助長やフレイルの増加も懸念されている。

**目的:** 本研究は、自転車運動を活用した8週間の身体活動が、中高齢者の健康的な自立した日常生活を営むための機能的能力を維持できるかどうかを検討した。

**方法:** 運動制限のない45歳以上の男女を運動群（n=9, 58.4±8.9歳）と対照群（n=10, 64.3±8.9歳）に分け、運動群にはRPE13による自転車運動を週2回以上、1回1時間程度実施した。介入前後で身体組成、年齢別新体力テスト、安静時及び運動中の心拍数とガス交換パラメーター、主観的運動強度、自転車一本橋バランス走テストなどを測定・調査した。

**結果:** 運動群では、介入後に**上体起こしと立ち幅跳びが有意に向上**し(p<0.05)、**自転車一本橋バランス走テストの走行時間が有意に遅くなった** (p<0.01)。また、**漸増運動負荷試験の運動継続時間も有意に延長した** (p<0.05)。一方、対照群では6分間歩行と最大酸素摂取量が有意に向上した (p<0.05)。運動群へのアンケート調査では、睡眠の質の低下が有意に認められた (p<0.01)。自転車運動中の平均運動強度は約62%であった。

**考察:** 自転車運動は、**動的バランス能力や下肢・体幹筋群の向上**に寄与する可能性が示唆された。運動継続時間の延長は、筋力改善や精神面の向上が影響したと考えられる。中高齢者の健康づくりには、運動強度を高めるよりも、**走行距離を増やし、長期的な運動習慣として楽しむことが重要**である。今後の課題として、低体力者へのシティーバイクの活用やリハビリテーションへの応用が挙げられる。

