---
title: "iskr2025"
---

# Conference

::: {.panel-tabset}
## En {.unnumbered}

International Society for Kaigo Research

## 日 {.unnumbered}

国際介護研究会

注: この会は、日本学術会議協力学術研究団体ではありません。

## De {.unnumbered}

International Society for Kaigo Research\
Internationale Gesellschaft für Kaigo-Forschung (Pflegeforschung in Japan)

## 中文 {.unnumbered}

国际护理研究协会

:::

# Conference Theme

::: {.panel-tabset}
## En  {.unnumbered}

Begin

## 日   {.unnumbered}

始めよう

## De  {.unnumbered}

Fangen Wir An!

## 中文　{.unnumbered}

来来来!!

:::


# Submit an Abstract

::: {.panel-tabset}
## En  {.unnumbered}

The Conference Programme Committee welcomes papers from a wide variety of interdisciplinary and theoretical perspectives, and submissions are organised into the streams and sub-streams listed below:

- Kaigo
- Rehabilitation
- Nursing
- Nutrituion
- Human Science
- User-Led Clinical Research

Submit an Abstract (English or Japanese) by 28 February 2025.

The maximum number of words for your abstract is 250 words (400 characters in Japanese).

Your submission will undergo peer review.

## 日   {.unnumbered}

大会プログラム委員会は、幅広い学際的・理論的視点からの論文を歓迎します。投稿は以下のストリームおよびサブストリームに分類されます。

- 介護学
- リハビリテーション学
- 看護学
- 栄養学
- 人間科学
- 当事者臨地研究

抄録 (英語または日本語) を2025年2月28日までに送信してください。

抄録は、400字以内（英語の場合 250 words）に納めてください。

抄録は、査読されます。

## De  {.unnumbered}

Der Programmausschuss der Konferenz begrüßt Beiträge aus einem breiten Spektrum interdisziplinärer und theoretischer Perspektiven. Die Beiträge werden in die folgenden Bereiche und Unterbereiche eingeteilt.

- Kaigo(Kaigo Wissenschaft)
- Rehabilitationsstidium
- Pflegestudium
- Ernährungswissenchaft
- Humanwissenschaften
- Persönliche Forschung zu den Betroffenen

Die Abstracts (auf Englisch oder Japanisch) müssen bis zum 28. Februar 2025 eingereicht werden.

Die Abstracts sollten 300 Wörter nicht überschreiten.

Die Abstracts werden einem Peer-Review unterzogen.
:::

[Submit Abstract](https://docs.google.com/forms/d/e/1FAIpQLSe97Kb2m-oIfZTT4Ms9y3KvHijg0thx6y6xJtIUYv2edcgbEg/viewform?usp=dialog)


# Programme

::: {.panel-tabset}
## En  {.unnumbered}

29 April 2025

Zoom (No camera required)

## 日   {.unnumbered}

2025年4月29日

Zoom (カメラは不要です)
:::

# Presentation

::: {.panel-tabset}
## En  {.unnumbered}

29 April 2025

Oral presentation: 10 minuts

Discussion: 20 minutes

## 日   {.unnumbered}

2025年4月29日

口頭発表: 10 分

質疑応答: 20 分

:::

# AI Usage

::: {.panel-tabset}
## En  {.unnumbered}

We do not permit the use of generative AI or AI-assisted tools to create or alter  manuscripts. 

Simple translation by DeepL or Google Translate is acceptable.

## 日   {.unnumbered}

AI または AI を利用したツールを使用した原稿作成を認めません。

DeepL または Google Translate による翻訳は認めます。

:::

# Assistance

::: {.panel-tabset}
## En  {.unnumbered}

Every Saturday 6:30-9:00 (JST), statistics, graph making and writing are supported online.

https://saturdaymorning.connpass.com/

## 日   {.unnumbered}

毎週土曜日 6:30-9:00、オンラインで統計、作図、原稿作成の支援をいたします。

https://saturdaymorning.connpass.com/
:::


